### ISSUE TITLE
Error getting links

### ISSUE THREAD

**Issue by ghost** [DotSee/DotSee.Discipline#3]
For our multilingual site, we are using virtual nodes.

When opening the home node, multiple errors are thrown:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotSee.Discipline.VirtualNodes.VirtualNodesUrlProvider.ConstructUrl(IUmbracoContext umbracoContext, Int32 id, Uri current, UrlMode mode, IPublishedContent content, String culture)
   at DotSee.Discipline.VirtualNodes.VirtualNodesUrlProvider.GetUrl(IPublishedContent content, UrlMode mode, String culture, Uri current)
   at Umbraco.Cms.Core.Routing.UrlProvider.<>c__DisplayClass14_0.<GetUrl>b__1(IUrlProvider provider)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Umbraco.Cms.Core.Routing.UrlProvider.GetUrl(IPublishedContent content, UrlMode mode, String culture, Uri current)
   at Umbraco.Cms.Core.PropertyEditors.MultiUrlPickerValueEditor.ToEditor(IProperty property, String culture, String segment)
```

This occurs for all nodes for which there is no published variant in that culture. 

Steps to reproduce
1. Create a node **Home**
2. Setup site in 2 languages (German & Dutch in this example)
3. Create a sub node **About us**
4. Publish node in German but not in Dutch
5. Open Home node in language Dutch
6. See logs

The error occurs in the method **ConstructUrl**  (DotSee.Discipline.VirtualNodes) on line 54 where the **base.GetUrl(content, mode, culture, current).Text;** is called. Here I believe no URL can be constructed for the current culture, resulting in null and leading to a null reference exception. 

Looking for some help on a good fix for this.

**Comment by sotirisf** [comment]
I tried to reproduce in various ways, but didn't see any errors in the logs. 

By what I understand you create and publish a Home node in both languages and an About Us subnode in German, but leave the Dutch About Us unpublished? Have I got it right? Also, is there a virtualnodes rule affecting this pair?

**Comment by ghost** [comment]
![image](https://github.com/DotSee/DotSee.Discipline/assets/102968988/adb8ebfc-bfcc-4b88-b9ec-e19a1712a460)

Yes you are right. There are virtual nodes above this (the red blocks are virtual nodes).

![image](https://github.com/DotSee/DotSee.Discipline/assets/102968988/5c4d16eb-f1df-4de8-8d21-a3072d797e9a)

**Comment by sotirisf** [comment]
However many attempts I made to reproduce this seemed to work fine. But looking at the error screenshot you posted, the problem seems to be related to your link picker, which is probably pointing to some not created node. I tested this and saw that it would throw an error there, although it would not repeat (or log anything for that matter) after publish. I'm not catching this error returning null so that it doesn't interfere with the picker, and published a new version. Please give it a try and see if it solves your issue.

**Comment by ghost** [comment]
Could you elaborate on that last part?

**Comment by sotirisf** [comment]
I see where you might get confused - typo on my side. I'm now catching any null reference exceptions and actually return null as a UrlProvider result (same as Umbraco does), so that when you select a "not created" node that participates in a VirtualNodes rule in your url picker, it won't throw an error.

**Comment by ghost** [comment]
Aha, does this require a code fix or was this a setting to adjust?

**Comment by sotirisf** [comment]
Just update your nuget package with the new version released yesterday.
